### ISSUE TITLE
Scripts in feedbackreporter/Server/Mantis do not support current Mantis (version 1.2)

### ISSUE THREAD

**Issue by seanm** [tcurdt/feedbackreporter#13]
The scripts in feedbackreporter/Server/Mantis support Mantis 1.1 but not the current 1.2.

An update would be nice. :)

**Comment by seanm** [comment]
@starlocke

**Comment by starlocke** [comment]
💡 I just had an idea on how to "maintain" multiple MantisBT support at the same time. Should be creating a new "Mantis-2.x" folder instead of patching the original "Mantis" folder. New folders for "1.2" and "1.3" needed as well. 😂

**Comment by seanm** [comment]
I don't see any value in keeping the current mantis code, as it only supports mantis version 1.1, which has known security vulnerabilities and isn't being maintained.  I believe that applies to all of 1.x too.

Supporting only the newest version (currently 2.5.1) is most sensible I believe.

**Comment by tcurdt** [comment]
Fine by me.
