### ISSUE TITLE
Preset the email address

### ISSUE THREAD

**Issue by tcurdt** [tcurdt/feedbackreporter#3]
Currently the default is to send the feedback report anonymously unless the user explicitly states his email address. It would be nice to (have at least an option to) use the user's email from the addressbook or from Mail.

**Comment by glg-satish-tripathi** [comment]
Testing the mutation

**Comment by glg-satish-tripathi** [comment]
Testing the mutation

**Comment by glg-satish-tripathi** [comment]
Testing the mutation

**Comment by glg-satish-tripathi** [comment]
Testing the mutation
