### ISSUE TITLE
Catching exceptions raised via Carbon event dispatch - eg menu-triggered exceptions

### ISSUE THREAD

**Issue by rowanbeentje** [tcurdt/feedbackreporter#7]
Currently, not all exceptions are caught by the exception handler - for example, any exception that's triggered by a menu action will log the exception to console with the following prefix:

HIToolbox: ignoring exception '<name>' that raised inside Carbon event dispatch

Does anyone have any ideas how to capture these exceptions?  The menu key equivalent is captured correctly, so it's purely the menu at fault here (easily testable in the test app by adding a menu with actions corresponding to the buttons - "Throw exception in thread" is caught, "Throw exception" isn't).

I've played around with setExceptionHandlingMask: with no success, though I haven't been 100% thorough with it.  (Incidentally, wouldn't the default/uncaught exception handler installation method be a good way to activate exception handling by default, without needing to set the principal class?)

**Comment by seanm** [comment]
Looks like something has changed in macOS (10.12 at least), because now provoking an exception from the menu items added in the test app are caught by and displayed by the feedbackreporter UI.
